### ISSUE TITLE
Update the code Jira release 9.x

### ISSUE THREAD

**Issue by javi-jamaa** [javi-jamaa/latch-plugin-jira#3]

**Comment by neo-sagittal** [comment]
Please include exactly one valid label on the ticket. e.g. neo-coder, neo-pjm, neo-pm

**Comment by neo-sagittal** [comment]
I'm on it! It might take a few minutes, I'll update here when it's done.

**Comment by neo-sagittal** [comment]
I have pushed some code for you to review here: https://github.com/javi-jamaa/latch-plugin-jira/pull/4
